### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by afzaalkarori** [NCAR/geocat-viz#49] opened 2021-10-15 09:03 UTC
I am having following Traceback while using NCL_corel_1.py code on ubuntu 18 LTE

Traceback (most recent call last):
  File "NCL_corel_1.py", line 90, in <module>
    gvutil.add_major_minor_ticks(ax, x_minor_per_major=4, y_minor_per_major=5, labelsize=16)
AttributeError: module 'geocat.viz.util' has no attribute 'add_major_minor_ticks'

Can you please help to get out of it.

Regards

Afzaal

**Comment by anissa111** [comment] 2022-02-15 23:52
@afzaalkarori and @QiaomeiFeng, I am unable to reproduce your errors. If this error is persisting, could you please provide your current conda environment with ```conda list```?

**Comment by QiaomeiFeng** [comment] 2022-02-16 00:17
Sure though it is redundant.

 - _anaconda_depends=2020.07=py38_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py38_0
  - affine=2.3.0=py_0
  - alabaster=0.7.12=py_0
  - anaconda=custom=py38_1
  - anaconda-client=1.7.2=py38_0
  - anaconda-navigator=2.0.4=py38_0
  - anaconda-project=0.8.4=py_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argh=0.26.2=py38_0
  - argon2-cffi=20.1.0=py38he774522_1
  - arviz=0.11.4=pyhd8ed1ab_0
  - asn1crypto=1.4.0=py_0
  - astroid=2.4.2=py38_0
  - astropy=4.0.2=py38he774522_0
  - async_generator=1.10=py_0
  - atomicwrites=1.4.0=py_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - autopep8=1.5.4=py_0
  - babel=2.8.1=pyhd3eb1b0_0
  - backcall=0.2.0=py_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - backports.shutil_get_terminal_size=1.0.0=py38_2
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - bcrypt=3.2.0=py38he774522_0
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - biopython=1.78=py38he774522_0
  - bitarray=1.6.1=py38h2bbff1b_0
  - bkcharts=0.2=py38_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - blosc=1.21.0=h0e60522_0
  - bokeh=2.4.2=py38haa95532_0
  - boost-cpp=1.74.0=h5b4e17d_5
  - boto=2.49.0=py38_0
  - bottleneck=1.3.2=py38h2a96729_1
  - brotlipy=0.7.0=py38he774522_1000
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2021.10.8=h5b45459_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=hb19e0ff_1008
  - cartopy=0.20.1=py38h436f59c_5
  - certifi=2021.10.8=py38haa244fe_1
  - cffi=1.14.3=py38h7a1dbc1_0
  - cfitsio=4.0.0=hd67004f_0
  - chardet=3.0.4=py38_1003
  - click=7.1.2=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cloudpickle=1.6.0=py_0
  - clyent=1.2.2=py38_1
  - colorama=0.4.4=py_0
  - colorcet=2.0.6=pyhd3eb1b0_0
  - comtypes=1.1.7=py38_1001
  - conda=4.11.0=py38haa244fe_0
  - conda-build=3.20.5=py38_1
  - conda-content-trust=0.1.1=pyhd3eb1b0_0
  - conda-env=2.6.0=1
  - conda-package-handling=1.7.3=py38h8cc25b3_1
  - conda-repo-cli=1.0.4=pyhd3eb1b0_0
  - conda-token=0.3.0=pyhd3eb1b0_0
  - conda-verify=3.4.2=py_1
  - console_shortcut=0.1.1=4
  - contextlib2=0.6.0.post1=py_0
  - convertdate=2.3.2=pyhd8ed1ab_0
  - cryptography=3.1.1=py38h7a1dbc1_0
  - curl=7.80.0=h2bbff1b_0
  - cycler=0.10.0=py38_0
  - cython=0.29.21=py38ha925a31_0
  - cytoolz=0.11.0=py38he774522_0
  - dask=2.30.0=py_0
  - dask-core=2.30.0=py_0
  - datashader=0.13.0=py_0
  - datashape=0.5.4=py38haa95532_1
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - diff-match-patch=20200713=py_0
  - distributed=2.30.1=py38haa95532_0
  - docutils=0.16=py38_1
  - entrypoints=0.3=py38_0
  - ephem=4.1=py38h294d835_1
  - et_xmlfile=1.0.1=py_1001
  - expat=2.4.2=h39d44d4_0
  - fastcache=1.1.0=py38he774522_0
  - fbprophet=0.7.1=py38h7ae7562_0
  - filelock=3.0.12=py_0
  - fiona=1.8.20=py38h19672d5_4
  - flake8=3.8.4=py_0
  - flask=1.1.2=py_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=h1989441_1005
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=hd328e21_0
  - freexl=1.0.6=ha8e266a_0
  - fsspec=0.8.3=py_0
  - future=0.18.2=py38_1
  - gdal=3.4.0=py38h117dad8_9
  - geocat-viz=2020.1.24.0=pyh39e3cac_0
  - geopandas=0.9.0=py_1
  - geopandas-base=0.9.0=py_1
  - geos=3.10.1=h39d44d4_1
  - geotiff=1.7.0=hc8731e1_5
  - geoviews=1.9.2=py_0
  - geoviews-core=1.9.2=py_0
  - get_terminal_size=1.0.0=h38e98db_0
  - gettext=0.19.8.1=ha2e2712_1008
  - gevent=20.9.0=py38he774522_0
  - glob2=0.7=py_0
  - gmpy2=2.0.8=py38h7edee0f_3
  - greenlet=0.4.17=py38he774522_0
  - hdf4=4.2.15=h0e5069d_3
  - hdf5=1.12.1=nompi_h2a0e4a3_103
  - heapdict=1.0.1=py_0
  - hijri-converter=2.2.2=pyhd8ed1ab_0
  - holidays=0.11.3.1=pyhd8ed1ab_0
  - holoviews=1.14.6=pyhd3eb1b0_1
  - html5lib=1.1=py_0
  - hvplot=0.7.3=pyh6c4a22f_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=68.2=h0e60522_0
  - idna=2.10=py_0
  - imageio=2.9.0=py_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - iniconfig=1.1.1=py_0
  - intel-openmp=2020.2=254
  - intervaltree=3.1.0=py_0
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.19.0=py38hd4e2768_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_1
  - isort=5.6.4=py_0
  - itsdangerous=1.1.0=py_0
  - jbig=2.1=h8d14728_2003
  - jdcal=1.4.1=py_0
  - jedi=0.17.1=py38_0
  - jinja2=2.11.2=py_0
  - joblib=0.17.0=py_0
  - jpeg=9d=h8ffe710_0
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py38_0
  - jupyterlab=2.2.6=py_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=1.2.0=py_0
  - kealib=1.4.14=h8995ca9_3
  - keyring=21.4.0=py38_1
  - kiwisolver=1.3.0=py38hd77b12b_0
  - korean_lunar_calendar=0.2.1=pyh9f0ad1d_0
  - krb5=1.19.2=hbae68bd_0
  - lazy-object-proxy=1.4.3=py38he774522_0
  - lcms2=2.12=h2a16943_0
  - lerc=3.0=h0e60522_0
  - libarchive=3.5.2=hb45042f_1
  - libclang=11.1.0=default_h5c34c98_1
  - libcurl=7.80.0=h86230a5_0
  - libdeflate=1.8=h8ffe710_0
  - libffi=3.4.2=h8ffe710_5
  - libgdal=3.4.0=hd873378_9
  - libglib=2.70.2=h3be07f2_0
  - libiconv=1.16=he774522_0
  - libkml=1.3.0=h9859afa_1014
  - liblief=0.10.1=ha925a31_0
  - libllvm9=9.0.1=h21ff451_0
  - libnetcdf=4.8.1=nompi_h1cc8e9d_101
  - libpng=1.6.37=h2a8f88b_0
  - libpq=14.1=hfcc5ef8_1
  - libpython=2.1=py38haa244fe_1
  - librttopo=1.1.0=he35e8ac_8
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h33f27b4_0
  - libspatialite=5.0.1=hf126459_12
  - libssh2=1.9.0=h7a1dbc1_1
  - libtiff=4.3.0=hd413186_2
  - libwebp-base=1.2.1=h8ffe710_0
  - libxml2=2.9.12=hf5bbc77_1
  - libxslt=1.1.34=he774522_0
  - libzip=1.8.0=hfed4ece_1
  - libzlib=1.2.11=h8ffe710_1013
  - llvmlite=0.34.0=py38h1a82afc_4
  - locket=0.2.0=py38_1
  - lunarcalendar=0.0.9=py_0
  - lxml=4.6.1=py38h1350720_0
  - lz4-c=1.9.3=h8ffe710_1
  - lzo=2.10=he774522_2
  - m2w64-binutils=2.25.1=5
  - m2w64-bzip2=1.0.6=6
  - m2w64-crt-git=5.0.0.4636.2595836=2
  - m2w64-gcc=5.3.0=6
  - m2w64-gcc-ada=5.3.0=6
  - m2w64-gcc-fortran=5.3.0=6
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gcc-objc=5.3.0=6
  - m2w64-gmp=6.1.0=2
  - m2w64-headers-git=5.0.0.4636.c0ad18a=2
  - m2w64-isl=0.16.1=2
  - m2w64-libiconv=1.14=6
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-make=4.1.2351.a80a8b8=2
  - m2w64-mpc=1.0.3=3
  - m2w64-mpfr=3.1.4=4
  - m2w64-pkg-config=0.29.1=2
  - m2w64-toolchain=5.3.0=7
  - m2w64-toolchain_win-64=2.4.0=0
  - m2w64-tools-git=5.0.0.4592.90b8472=2
  - m2w64-windows-default-manifest=6.4=3
  - m2w64-winpthreads-git=5.0.0.4634.697f757=2
  - m2w64-zlib=1.2.8=10
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markdown=3.3.4=py38haa95532_0
  - markupsafe=1.1.1=py38he774522_0
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py38hba9282a_0
  - mccabe=0.6.1=py38_1
  - menuinst=1.4.16=py38he774522_1
  - mistune=0.8.4=py38he774522_1000
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38hb782905_0
  - mkl_fft=1.2.0=py38h45dec08_0
  - mkl_random=1.1.1=py38h47e9c7a_0
  - mock=4.0.2=py_0
  - more-itertools=8.6.0=pyhd3eb1b0_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.1.0=py38_0
  - msgpack-python=1.0.0=py38h74a9793_1
  - msys2-conda-epoch=20160418=1
  - multipledispatch=0.6.0=py38_0
  - munch=2.5.0=py_0
  - navigator-updater=0.2.1=py38_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.0.8=py_0
  - nest-asyncio=1.4.2=pyhd3eb1b0_0
  - networkx=2.5=py_0
  - nltk=3.5=py_0
  - nose=1.3.7=py38_2
  - notebook=6.1.4=py38_0
  - numba=0.51.2=py38hf9181ef_1
  - numexpr=2.7.1=py38h25d0782_0
  - numpy=1.19.2=py38hadc3359_0
  - numpy-base=1.19.2=py38ha3acd2a_0
  - numpydoc=1.1.0=pyhd3eb1b0_1
  - olefile=0.46=py_0
  - openjpeg=2.4.0=hb211442_1
  - openpyxl=3.0.5=py_0
  - openssl=1.1.1l=h8ffe710_0
  - pandas=1.1.3=py38ha925a31_0
  - pandoc=2.11=h9490d1a_0
  - pandocfilters=1.4.3=py38haa95532_1
  - param=1.12.0=pyhd3eb1b0_0
  - paramiko=2.7.2=py_0
  - parso=0.7.0=py_0
  - partd=1.1.0=py_0
  - path=15.0.0=py38_0
  - path.py=12.5.0=0
  - pathlib2=2.3.5=py38_0
  - pathtools=0.1.2=py_1
  - patsy=0.5.1=py38_0
  - pcre=8.45=h0e60522_0
  - pep8=1.7.1=py38_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=8.0.1=py38h4fa10fc_0
  - pip=20.2.4=py38haa95532_0
  - pixman=0.40.0=h8ffe710_0
  - pkginfo=1.6.1=py38haa95532_0
  - plotly=5.1.0=pyhd3eb1b0_0
  - pluggy=0.13.1=py38_0
  - ply=3.11=py38_0
  - pooch=1.5.2=pyhd8ed1ab_0
  - poppler=21.11.0=h24fffdf_0
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.1=h1c22c4f_1
  - powershell_shortcut=0.0.1=3
  - proj=8.2.0=h1cfcee9_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - psutil=5.7.2=py38he774522_0
  - py=1.9.0=py_0
  - py-lief=0.10.1=py38ha925a31_0
  - pycodestyle=2.6.0=py_0
  - pycosat=0.6.3=py38he774522_0
  - pycparser=2.20=py_2
  - pyct=0.4.8=py38_0
  - pycurl=7.43.0.6=py38h7a1dbc1_0
  - pydocstyle=5.1.1=py_0
  - pyflakes=2.2.0=py_0
  - pygeos=0.12.0=py38hd784ac2_0
  - pygments=2.7.2=pyhd3eb1b0_0
  - pylint=2.6.0=py38_0
  - pymeeus=0.5.10=pyhd8ed1ab_0
  - pynacl=1.4.0=py38h62dcd97_1
  - pyodbc=4.0.30=py38ha925a31_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyproj=3.3.0=py38h12f9802_0
  - pyqt=5.12.3=py38haa244fe_8
  - pyqt-impl=5.12.3=py38h885f38d_8
  - pyqt5-sip=4.19.18=py38h885f38d_8
  - pyqtchart=5.12=py38h885f38d_8
  - pyqtwebengine=5.12.1=py38h885f38d_8
  - pyreadline=2.1=py38_1
  - pyrsistent=0.17.3=py38he774522_0
  - pyshp=2.1.3=pyh44b312d_0
  - pysocks=1.7.1=py38_0
  - pystan=2.19.1.1=py38h02adce6_3
  - pytables=3.6.1=py38h7deab4d_5
  - pytest=6.1.1=py38_0
  - python=3.8.5=h5fd99cc_1
  - python-dateutil=2.8.1=py_0
  - python-jsonrpc-server=0.4.0=py_0
  - python-language-server=0.35.1=py_0
  - python-libarchive-c=2.9=py_0
  - python_abi=3.8=2_cp38
  - pytz=2020.1=py_0
  - pyviz_comms=2.1.0=pyhd8ed1ab_0
  - pywavelets=1.1.1=py38he774522_2
  - pywin32=227=py38he774522_1
  - pywin32-ctypes=0.2.0=py38_1000
  - pywinpty=0.5.7=py38_0
  - pyyaml=5.3.1=py38he774522_1
  - pyzmq=19.0.2=py38ha925a31_1
  - qdarkstyle=2.8.1=py_0
  - qt=5.12.9=h5909a2a_4
  - qtawesome=1.0.1=py_0
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - rasterio=1.2.10=py38h48edd3a_3
  - regex=2020.10.15=py38he774522_0
  - regionmask=0.8.0=pyhd8ed1ab_1
  - requests=2.24.0=py_0
  - rope=0.18.0=py_0
  - rtree=0.9.4=py38h21ff451_1
  - ruamel_yaml=0.15.87=py38he774522_1
  - scikit-image=0.17.2=py38h1e1f486_0
  - scikit-learn=0.23.2=py38h47e9c7a_0
  - scipy=1.5.2=py38h14eb087_0
  - seaborn=0.11.0=py_0
  - send2trash=1.5.0=py38_0
  - setuptools=50.3.1=py38haa95532_1
  - shapely=1.8.0=py38hd784ac2_4
  - simplegeneric=0.8.1=py38_2
  - singledispatch=3.4.0.3=py_1001
  - sip=4.19.13=py38ha925a31_0
  - six=1.15.0=py38haa95532_0
  - snappy=1.1.8=h33f27b4_0
  - snowballstemmer=2.0.0=py_0
  - snuggs=1.4.7=py_0
  - sortedcollections=1.2.1=py_0
  - sortedcontainers=2.2.2=py_0
  - soupsieve=2.0.1=py_0
  - sphinx=3.2.1=py_0
  - sphinxcontrib=1.0=py38_1
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sphinxcontrib-websupport=1.2.4=py_0
  - spyder=4.1.5=py38_0
  - spyder-kernels=1.9.4=py38_0
  - sqlalchemy=1.3.20=py38h2bbff1b_0
  - sqlite=3.37.0=h8ffe710_0
  - statsmodels=0.12.0=py38he774522_0
  - sympy=1.6.2=py38haa95532_1
  - tbb=2021.4.0=h59b6b97_0
  - tblib=1.7.0=py_0
  - tenacity=8.0.1=py38haa95532_0
  - terminado=0.9.1=py38_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2020.10.1=py38h8c2d366_2
  - tiledb=2.5.3=h95dad36_0
  - tk=8.6.10=he774522_0
  - toml=0.10.1=py_0
  - toolz=0.11.1=py_0
  - tornado=6.0.4=py38he774522_1
  - tqdm=4.50.2=py_0
  - traitlets=5.0.5=py_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - ucrt=10.0.20348.0=h57928b3_0
  - ujson=4.0.1=py38ha925a31_0
  - unicodecsv=0.14.1=py38_0
  - urllib3=1.25.11=py_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.29.30037=h902a5da_5
  - watchdog=0.10.3=py38_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - werkzeug=1.0.1=py_0
  - wheel=0.35.1=py_0
  - widgetsnbextension=3.5.1=py38_0
  - win_inet_pton=1.1.0=py38_0
  - win_unicode_console=0.5=py38_0
  - wincertstore=0.2=py38_0
  - winpty=0.4.3=4
  - xerces-c=3.2.3=h0e60522_4
  - xlrd=1.2.0=py_0
  - xlsxwriter=1.3.7=py_0
  - xlwings=0.20.8=py38_0
  - xlwt=1.3.0=py38_0
  - xmltodict=0.12.0=pyhd3eb1b0_0
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - yapf=0.30.0=py_0
  - zeromq=4.3.2=ha925a31_3
  - zict=2.0.0=py_0
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h8ffe710_1013
  - zope=1.0=py38_1
  - zope.event=4.5.0=py38_0
  - zope.interface=5.1.2=py38he774522_0
  - zstd=1.5.0=h6255e5f_0

**Comment by anissa111** [comment] 2022-02-16 00:26
@QiaomeiFeng I think I see your issue. I suggest that you update to the latest version of geocat-viz, which currently is 2021.08.0. There will likely be an additional release in the next week or so.

**Comment by zhilonglu** [comment] 2022-05-05 10:04
Actually，I have the error, 'AttributeError: module 'geocat.viz.util' has no attribute 'set_axes_limits_and_ticks'
I install conda, and use conda to install geocat.viz, when i try to run NCL_bar_11.py, the above error occurs.

**Comment by anissa111** [comment] 2022-05-23 17:21
@zhilonglu Hello! Sorry for the delayed response. We have released a new version, v2022.05.0, try upgrading to the latest version and let us know if the issue persists.

**Comment by pilotchute** [comment] 2022-08-17 19:01
No reply to suggested fix for 3 months, going to close this as resolved.

**Closed by pilotchute** 2022-08-17 19:01 UTC
Labels: high priority, support
